port: 7890
socks-port: 7891
mixed-port: 7888
redir-port: 7891
tproxy-port: 1536
mode: rule
allow-lan: false
geodata-mode: true
unified-delay: true
log-level: warning
ipv6: false
external-controller: localhost:9090
external-ui: yacd
enable-process: false

profile:
  store-selected: true
  store-fake-ip: false

tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
  auto-route: true
  auto-detect-interface: true

sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - Mijia Cloud
    - +.apple.com
  force-domain: []
  port-whitelist:
    - 80
    - 443
    - 8000-9000

hosts:
  +.clash.meta: 127.0.0.1

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  use-hosts: true
  fake-ip-filter:
    - connect.rom.miui.com
    - +.gstatic.com
    - "*"
    - +.lan
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - lens.l.google.com
    - "*.mcdn.bilivideo.cn"
  fake-ip-range: 28.0.0.1/8
  proxy-server-nameserver:
    - https://114.114.114.114/dns-query
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  default-nameserver:
    - https://114.114.114.114/dns-query
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  nameserver:
    - https://114.114.114.114/dns-query
    - https://223.5.5.5/dns-query
    - https://1.12.12.12/dns-query
  fallback:
    - tcp://185.222.222.222#Proxy
    - tcp://94.140.15.15#Proxy
    - tcp://8.8.4.4#Proxy
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - "!CN"

proxy-providers:
  Licht:
    type: file
    path: ./configs/Licht.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  iKuuu:
    type: file
    path: ./configs/iKuuu.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

proxy-groups:
  - name: 🚀
    type: select
    use:
      - Licht
      - iKuuu

rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400

# 黑名单模式，漏网之鱼代理
rules:
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,🚀
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,🚀
  - GEOIP,LAN,DIRECT
  - GEOIP,PRIVATE,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,🚀

# 白名单模式，漏网之鱼直连
# rules:
#   - RULE-SET,applications,DIRECT
#   - DOMAIN,clash.razord.top,DIRECT
#   - DOMAIN,yacd.haishan.me,DIRECT
#   - RULE-SET,private,DIRECT
#   - RULE-SET,reject,REJECT
#   - RULE-SET,tld-not-cn,PROXY
#   - RULE-SET,gfw,PROXY
#   - RULE-SET,greatfire,PROXY
#   - RULE-SET,telegramcidr,PROXY
#   - MATCH,DIRECT